"""Deterministic rendering of the shared Cogem communication window."""

from __future__ import annotations

from pathlib import Path
from typing import Mapping

from .goal import assess_goal
from .state import CogemState


OPERATOR_NOTES_START = "<!-- COGEM:OPERATOR_NOTES:START -->"
OPERATOR_NOTES_END = "<!-- COGEM:OPERATOR_NOTES:END -->"
_ACTIVE_STATUSES = {"proposed", "ready", "assigned", "in_progress", "blocked", "review_ready", "review_failed", "approved"}


def _cell(value: object) -> str:
    text = str(value).replace("\n", "<br>").replace("|", "\\|")
    return text if text else "—"


def _table(headers: tuple[str, ...], rows: list[tuple[object, ...]]) -> list[str]:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    if not rows:
        lines.append("| " + " | ".join("—" for _ in headers) + " |")
        return lines
    for row in rows:
        lines.append("| " + " | ".join(_cell(value) for value in row) + " |")
    return lines


def extract_operator_notes(text: str) -> str:
    if OPERATOR_NOTES_START not in text or OPERATOR_NOTES_END not in text:
        return ""
    after = text.split(OPERATOR_NOTES_START, 1)[1]
    notes = after.split(OPERATOR_NOTES_END, 1)[0]
    return notes.strip("\n")


def render_comm(
    state: CogemState,
    *,
    objective: str,
    phase: str,
    graph_summary: Mapping[str, int] | None = None,
    goal_actions: Mapping[str, str] | None = None,
    operator_notes: str = "",
    recent_message_limit: int = 20,
) -> str:
    graph_summary = graph_summary or {}
    goal_actions = goal_actions or {}
    tracked_goals = sorted(
        state.goals.values(),
        key=lambda goal: (goal.status == "achieved", goal.goal_id),
    )
    active_goal = next(
        (
            goal
            for goal in tracked_goals
            if goal_actions.get(goal.goal_id, "complete" if goal.status == "achieved" else "check") != "complete"
        ),
        None,
    )
    effective_objective = active_goal.objective if active_goal else objective
    active_tasks = [task for task in state.tasks.values() if task.status in _ACTIVE_STATUSES]
    active_tasks.sort(key=lambda task: (task.priority != "critical", task.priority != "high", task.task_id))

    lines: list[str] = [
        "# Comm.md",
        "",
        "> Generated by Cogem from `.agents/` records. The persistent Leader owns this file.",
        "> Edit only the Operator Notes block; all other manual changes may be overwritten.",
        "",
        "## Current Objective",
        "",
        effective_objective.strip() or "No objective configured.",
        "",
        "## Current Phase",
        "",
        phase.strip() or "unspecified",
        "",
        "## Active Goals",
        "",
    ]

    goal_rows = [
        (
            goal.goal_id,
            goal.status,
            goal.iteration,
            f"{sum(1 for item in goal.criteria if item.status == 'pass' and item.evidence)}/{len(goal.criteria)}",
            ", ".join(goal.task_ids) or "—",
            "; ".join(goal.current_gaps) or goal.blocker or "—",
        )
        for goal in tracked_goals
        if goal_actions.get(goal.goal_id, "complete" if goal.status == "achieved" else "check") != "complete"
    ]
    lines.extend(_table(("Goal", "Status", "Iteration", "Criteria", "Tasks", "Current gap or blocker"), goal_rows))

    lines.extend(["", "## Goal Loop", ""])
    loop_rows = [
        (
            goal.goal_id,
            goal_actions.get(goal.goal_id, "complete" if goal.status == "achieved" else "run goal-check"),
            "yield"
            if goal_actions.get(goal.goal_id, "complete" if goal.status == "achieved" else "check") == "complete"
            else "continue",
        )
        for goal in tracked_goals
    ]
    lines.extend(_table(("Goal", "Next gate", "Leader behavior"), loop_rows))

    lines.extend(["", "## Active Agents", ""])
    agent_rows: list[tuple[object, ...]] = []
    for agent_id in sorted({task.owner for task in active_tasks} | {message.agent_id for message in state.messages[-recent_message_limit:]}):
        owned = [task.task_id for task in active_tasks if task.owner == agent_id]
        agent_rows.append((agent_id, ", ".join(owned) or "message-only", len(owned)))
    lines.extend(_table(("Agent", "Active responsibility", "Task count"), agent_rows))

    lines.extend(["", "## Active Tasks", ""])
    task_rows = [
        (
            task.task_id,
            task.title,
            task.owner,
            task.status,
            task.review_level,
            task.review_tree_hash or "—",
            ", ".join(task.depends_on) or "—",
            task.writing_lease,
        )
        for task in active_tasks
    ]
    lines.extend(_table(("Task", "Title", "Owner", "Status", "Review level", "Review tree hash", "Dependencies", "Writing lease"), task_rows))

    lines.extend(["", "## File and Section Ownership", ""])
    ownership_rows: list[tuple[object, ...]] = []
    for task in active_tasks:
        for path in task.write_set:
            ownership_rows.append((path, task.owner, task.task_id, task.writing_lease, "source" if task.source_write else "generated/state"))
    ownership_rows.sort(key=lambda row: (str(row[0]), str(row[2])))
    lines.extend(_table(("Path", "Owner", "Task", "Lease", "Write class"), ownership_rows))

    lines.extend(["", "## Dependency Order", ""])
    dependency_rows = [
        (task.task_id, ", ".join(task.depends_on) or "ready without predecessors")
        for task in active_tasks
    ]
    lines.extend(_table(("Task", "Must follow"), dependency_rows))

    lines.extend(["", "## Shared Decisions", ""])
    decision_rows = [
        (decision.decision_id, decision.title, decision.status, decision.owner, decision.rationale, ", ".join(decision.affected_paths))
        for decision in state.decisions.values()
        if decision.status in {"proposed", "accepted"}
    ]
    lines.extend(_table(("Decision", "Title", "Status", "Owner", "Rationale", "Affected paths"), decision_rows))

    lines.extend(["", "## Pending Handoffs", ""])
    handoff_rows = [
        (handoff.handoff_id, handoff.from_agent, handoff.to_agent, handoff.task_id, handoff.status, handoff.summary)
        for handoff in state.handoffs.values()
        if handoff.status in {"pending", "accepted"}
    ]
    lines.extend(_table(("Handoff", "From", "To", "Task", "Status", "Summary"), handoff_rows))

    lines.extend(["", "## Open Blockers", ""])
    blocker_rows: list[tuple[object, ...]] = []
    for task in active_tasks:
        if task.status == "blocked":
            blocker_rows.append((task.task_id, task.owner, "Task status is blocked"))
    for message in state.messages:
        if message.kind == "blocker":
            blocker_rows.append((message.task_id or "—", message.agent_id, message.body))
    lines.extend(_table(("Task", "Reported by", "Blocker"), blocker_rows))

    lines.extend(["", "## Validation Status", ""])
    report_rows = [
        (
            report.report_id,
            report.kind,
            report.status,
            report.agent_id,
            report.task_id or report.goal_id or "—",
            report.review_proof.engine if report.review_proof else "—",
            report.review_proof.session_id if report.review_proof else "—",
            report.review_proof.reviewed_tree_hash if report.review_proof else "—",
            report.summary,
        )
        for report in state.reports
    ]
    lines.extend(_table(("Report", "Kind", "Status", "Agent", "Target", "Engine", "Session", "Review hash", "Summary"), report_rows))

    lines.extend(["", "## Graphify Summary", ""])
    lines.extend(
        _table(
            ("Metric", "Value"),
            [
                ("Nodes", graph_summary.get("nodes", 0)),
                ("Edges", graph_summary.get("edges", 0)),
                ("Broken links", graph_summary.get("broken_links", 0)),
                ("Invalid JSON", graph_summary.get("invalid_json", 0)),
                ("Unsafe task pairs", graph_summary.get("unsafe_pairs", 0)),
            ],
        )
    )

    lines.extend(["", "## Recent Agent Messages", ""])
    messages = list(state.messages[-max(0, recent_message_limit):])
    messages.reverse()
    message_rows = [
        (message.created_at, message.agent_id, message.task_id or "—", message.kind, message.body)
        for message in messages
    ]
    lines.extend(_table(("Time", "Agent", "Task", "Kind", "Message"), message_rows))

    lines.extend(
        [
            "",
            "## Operator Notes",
            "",
            OPERATOR_NOTES_START,
            operator_notes.rstrip(),
            OPERATOR_NOTES_END,
            "",
        ]
    )
    return "\n".join(lines)


def write_comm(
    path: Path,
    state: CogemState,
    *,
    objective: str,
    phase: str,
    graph_summary: Mapping[str, int] | None = None,
    recent_message_limit: int = 20,
) -> str:
    destination = Path(path)
    existing_notes = ""
    if destination.exists():
        existing_notes = extract_operator_notes(destination.read_text(encoding="utf-8"))
    goal_actions: dict[str, str] = {}
    root = destination.resolve().parent
    for goal_id in state.goals:
        try:
            goal_actions[goal_id] = assess_goal(root, goal_id).next_action
        except (OSError, ValueError):
            goal_actions[goal_id] = "invalid"
    rendered = render_comm(
        state,
        objective=objective,
        phase=phase,
        graph_summary=graph_summary,
        goal_actions=goal_actions,
        operator_notes=existing_notes,
        recent_message_limit=recent_message_limit,
    )
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(rendered, encoding="utf-8")
    return rendered
